export const SET_PRODUCTS_DATA = "SET_PRODUCTS_DATA";
export const SET_API_ERROR = "API_ERROR";
export const SET_LOADING = "SET_LOADING";
export const SET_SINGLE_PRODUCT_LOADING = "SET_SINGLE_PRODUCT_LOADING";
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT";